#!/bin/bash
# Portyfoul Secrets Management Script
#
# Manages AWS Secrets Manager secrets for the Portyfoul application.
# Supports creating new secrets and updating existing secrets.
#
# Usage:
#   ./scripts/create-secrets.sh [options]
#
# Examples:
#   # Create all secrets for dev environment (interactive)
#   ./scripts/create-secrets.sh --region us-east-2 --env dev
#
#   # Update only Finnhub API key
#   ./scripts/create-secrets.sh --update finnhub --region us-east-2 --env dev
#
#   # Update CoinGecko API key
#   ./scripts/create-secrets.sh --update coingecko --region us-east-2 --env dev
#
#   # Non-interactive mode (provide API key via argument)
#   ./scripts/create-secrets.sh --update finnhub --value YOUR_API_KEY --region us-east-2 --env dev

set -e

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[0;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Default values
REGION="us-east-2"
ENVIRONMENT="dev"
PROJECT_NAME="portyfoul"
UPDATE_SECRET=""
SECRET_VALUE=""
INTERACTIVE=true

# Functions
function log_info() {
    echo -e "${BLUE}ℹ ${NC}$1"
}

function log_success() {
    echo -e "${GREEN}✓${NC} $1"
}

function log_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

function log_error() {
    echo -e "${RED}✗${NC} $1" >&2
}

function show_help() {
    cat << EOF
Portyfoul Secrets Management Script

Manages AWS Secrets Manager secrets for the Portyfoul application.

USAGE:
    ./scripts/create-secrets.sh [OPTIONS]

OPTIONS:
    --region REGION       AWS region (default: us-east-2)
    --env ENVIRONMENT     Environment name (dev, staging, prod) (default: dev)
    --update SECRET       Update specific secret (jwt, finnhub, coingecko, rds)
    --value VALUE         Secret value (for non-interactive mode)
    --help                Show this help message

EXAMPLES:
    # Create all secrets for dev environment (interactive)
    ./scripts/create-secrets.sh --region us-east-2 --env dev

    # Update Finnhub API key (interactive)
    ./scripts/create-secrets.sh --update finnhub --region us-east-2 --env dev

    # Update Finnhub API key (non-interactive)
    ./scripts/create-secrets.sh --update finnhub --value YOUR_API_KEY --region us-east-2 --env dev

    # Update CoinGecko API key
    ./scripts/create-secrets.sh --update coingecko --region us-east-2 --env dev

SECRETS MANAGED:
    jwt        - JWT signing secret for authentication
    finnhub    - Finnhub API key for stock price data (REQUIRED)
    coingecko  - CoinGecko API key for crypto price data (OPTIONAL)
    rds        - RDS database credentials (auto-generated, rarely updated manually)

API KEY INFORMATION:
    Finnhub API Key:
        - Required for stock price updates
        - Get free tier at: https://finnhub.io/register
        - Free tier includes 60 API calls/minute

    CoinGecko API Key:
        - Optional - free tier works without API key
        - Higher rate limits with API key
        - Get at: https://www.coingecko.com/en/api

NOTES:
    - RDS credentials are auto-generated by CloudFormation
    - JWT secret is auto-generated by CloudFormation
    - Only Finnhub and CoinGecko keys typically need manual updates
    - After updating secrets, redeploy ECS services to pick up changes

EOF
}

function check_aws_cli() {
    if ! command -v aws &> /dev/null; then
        log_error "AWS CLI is not installed. Please install it first."
        log_info "Install: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html"
        exit 1
    fi
}

function check_aws_credentials() {
    if ! aws sts get-caller-identity --region "$REGION" &> /dev/null; then
        log_error "AWS credentials not configured or invalid."
        log_info "Run: aws configure"
        exit 1
    fi
}

function secret_exists() {
    local secret_name="$1"
    if aws secretsmanager describe-secret \
        --secret-id "$secret_name" \
        --region "$REGION" &> /dev/null; then
        return 0
    else
        return 1
    fi
}

function create_or_update_secret() {
    local secret_name="$1"
    local secret_value="$2"
    local description="$3"

    if secret_exists "$secret_name"; then
        log_info "Updating existing secret: $secret_name"
        aws secretsmanager update-secret \
            --secret-id "$secret_name" \
            --secret-string "$secret_value" \
            --region "$REGION" > /dev/null
        log_success "Updated secret: $secret_name"
    else
        log_info "Creating new secret: $secret_name"
        aws secretsmanager create-secret \
            --name "$secret_name" \
            --description "$description" \
            --secret-string "$secret_value" \
            --region "$REGION" > /dev/null
        log_success "Created secret: $secret_name"
    fi
}

function get_secret_value() {
    local secret_name="$1"
    aws secretsmanager get-secret-value \
        --secret-id "$secret_name" \
        --region "$REGION" \
        --query 'SecretString' \
        --output text 2>/dev/null || echo ""
}

function update_jwt_secret() {
    local secret_name="${PROJECT_NAME}/${ENVIRONMENT}/jwt-secret"

    if secret_exists "$secret_name"; then
        log_warning "JWT secret already exists: $secret_name"
        read -p "Do you want to regenerate it? (y/N): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            log_info "Skipping JWT secret update"
            return
        fi
    fi

    log_info "Generating new JWT secret (256-bit random string)..."
    local jwt_secret=$(openssl rand -base64 32)

    create_or_update_secret "$secret_name" "$jwt_secret" "JWT signing secret for Portyfoul authentication"
    log_warning "NOTE: After updating JWT secret, all existing user sessions will be invalidated"
}

function update_finnhub_secret() {
    local secret_name="${PROJECT_NAME}/${ENVIRONMENT}/finnhub-api-key"
    local api_key="$SECRET_VALUE"

    if [ -z "$api_key" ]; then
        log_info "Finnhub API Key - Required for stock price updates"
        log_info "Get your free API key at: https://finnhub.io/register"
        echo

        # Show current value if exists
        if secret_exists "$secret_name"; then
            local current_value=$(get_secret_value "$secret_name")
            if [ ! -z "$current_value" ]; then
                log_info "Current value: $current_value"
            fi
        fi

        read -p "Enter your Finnhub API key: " api_key

        if [ -z "$api_key" ]; then
            log_error "API key cannot be empty"
            exit 1
        fi
    fi

    create_or_update_secret "$secret_name" "$api_key" "Finnhub API key for stock price data"
}

function update_coingecko_secret() {
    local secret_name="${PROJECT_NAME}/${ENVIRONMENT}/coingecko-api-key"
    local api_key="$SECRET_VALUE"

    if [ -z "$api_key" ]; then
        log_info "CoinGecko API Key - Optional (free tier works without API key)"
        log_info "Get API key at: https://www.coingecko.com/en/api"
        echo

        # Show current value if exists
        if secret_exists "$secret_name"; then
            local current_value=$(get_secret_value "$secret_name")
            if [ ! -z "$current_value" ]; then
                log_info "Current value: $current_value"
            fi
        fi

        read -p "Enter your CoinGecko API key (or press Enter to use free tier): " api_key

        # If empty, use placeholder
        if [ -z "$api_key" ]; then
            api_key="OPTIONAL-COINGECKO-API-KEY"
            log_info "Using placeholder value for CoinGecko API key"
        fi
    fi

    create_or_update_secret "$secret_name" "$api_key" "CoinGecko API key for cryptocurrency price data"
}

function update_rds_secret() {
    local secret_name="${PROJECT_NAME}/${ENVIRONMENT}/rds/credentials"

    log_warning "RDS credentials are typically auto-generated by CloudFormation"
    log_warning "Manual update is rarely needed and may break database connections"
    echo
    read -p "Are you sure you want to update RDS credentials? (y/N): " -n 1 -r
    echo

    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        log_info "Skipping RDS credentials update"
        return
    fi

    read -p "Enter database username: " db_user
    read -s -p "Enter database password: " db_password
    echo

    if [ -z "$db_user" ] || [ -z "$db_password" ]; then
        log_error "Username and password cannot be empty"
        exit 1
    fi

    local credentials="{\"username\":\"$db_user\",\"password\":\"$db_password\"}"
    create_or_update_secret "$secret_name" "$credentials" "RDS PostgreSQL credentials"

    log_warning "NOTE: You must update the database user/password in RDS to match!"
}

function create_all_secrets() {
    log_info "Creating all secrets for environment: $ENVIRONMENT"
    echo

    # JWT Secret
    log_info "=== JWT Secret ==="
    update_jwt_secret
    echo

    # Finnhub API Key
    log_info "=== Finnhub API Key (REQUIRED) ==="
    update_finnhub_secret
    echo

    # CoinGecko API Key
    log_info "=== CoinGecko API Key (OPTIONAL) ==="
    update_coingecko_secret
    echo

    log_success "All secrets created/updated successfully!"
    log_info ""
    log_info "Next steps:"
    log_info "1. Verify secrets in AWS Console or with: aws secretsmanager list-secrets --region $REGION"
    log_info "2. Redeploy ECS services to pick up secret changes: ./scripts/deploy.py"
}

function list_secrets() {
    log_info "Listing secrets for $PROJECT_NAME/$ENVIRONMENT in $REGION:"
    echo

    local secrets=(
        "${PROJECT_NAME}/${ENVIRONMENT}/jwt-secret"
        "${PROJECT_NAME}/${ENVIRONMENT}/finnhub-api-key"
        "${PROJECT_NAME}/${ENVIRONMENT}/coingecko-api-key"
        "${PROJECT_NAME}/${ENVIRONMENT}/rds/credentials"
    )

    for secret_name in "${secrets[@]}"; do
        if secret_exists "$secret_name"; then
            local value=$(get_secret_value "$secret_name")
            local value_length=${#value}
            log_success "$secret_name (${value_length} characters)"
        else
            log_warning "$secret_name (not found)"
        fi
    done
}

# Parse command line arguments
while [[ $# -gt 0 ]]; do
    case $1 in
        --region)
            REGION="$2"
            shift 2
            ;;
        --env|--environment)
            ENVIRONMENT="$2"
            shift 2
            ;;
        --update)
            UPDATE_SECRET="$2"
            shift 2
            ;;
        --value)
            SECRET_VALUE="$2"
            INTERACTIVE=false
            shift 2
            ;;
        --list)
            LIST_SECRETS=true
            shift
            ;;
        --help|-h)
            show_help
            exit 0
            ;;
        *)
            log_error "Unknown option: $1"
            echo
            show_help
            exit 1
            ;;
    esac
done

# Main execution
echo
log_info "Portyfoul Secrets Management"
log_info "Region: $REGION"
log_info "Environment: $ENVIRONMENT"
echo

# Check prerequisites
check_aws_cli
check_aws_credentials

# List secrets if requested
if [ "$LIST_SECRETS" = true ]; then
    list_secrets
    exit 0
fi

# Update specific secret or create all
if [ ! -z "$UPDATE_SECRET" ]; then
    case "$UPDATE_SECRET" in
        jwt)
            update_jwt_secret
            ;;
        finnhub)
            update_finnhub_secret
            ;;
        coingecko)
            update_coingecko_secret
            ;;
        rds)
            update_rds_secret
            ;;
        *)
            log_error "Unknown secret: $UPDATE_SECRET"
            log_info "Valid secrets: jwt, finnhub, coingecko, rds"
            exit 1
            ;;
    esac
else
    create_all_secrets
fi

echo
log_success "Done!"
